### ISSUE TITLE
if this was serious and wanted to be private you'd pay for a repo, this is just stolen altis source

### ISSUE THREAD

**Issue by ghost** [MTTPAM/PublicRelease#2]
On top of that; This isn't for chatter; this is meant for serious issues that need addressing. all this github is for is pass out updates

**Comment by linktlh** [comment]
lol This is supposed to be an open source modification for FUN; not supposed to be a full-on private server. just something for people to mess around with; they never claimed that they own it. its MTTPAM; Mr T's Toontown Project Altis Modifications. Thank you; have a nice day.
